### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by Super-Baleine** [Ne0blast/cosmos#3]
in
https://github.com/Ne0blast/cosmos/blob/master/js/window.js
variable dispo --> layout
Or you code in french ?

**Comment by Ne0blast** [comment]
"Disposition" is the same in english :)
You can use "disposition" or "layout" but i prefer transparents words :D

**Comment by Super-Baleine** [comment]
Okay x)

**Comment by Ne0blast** [comment]
Still thanks :)
